services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - "5666:5432" # expose Postgres to host
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
